name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  health-check-job:
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check python version
        run: python3 --version
      - name: Check python version
        run: make run-local


