name: Django CI/CD

on:
  push:
    branches:
      - main

jobs:
  health-check-job:
    runs-on: ubuntu-latest # os for running the job
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup python environment
        uses: actions/setup-python@v2
        with:
          python-version: '3.10'
      - name: Check python version
        run: python3 --version
      - name: install dependecies
        run: pip install -r requirements.txt
      - name: prepare env
        run: make copy-env
      - name: run migrations
        run: cd django-with-tests && python manage.py migrate
      - name: run app
        run: python manage.py runserver


